# Generated by Django 5.1.7 on 2025-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0002_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
